// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjsugiuabyecemeaccku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqc3VnaXVhYnllY2VtZWFjY2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NzMyMTEsImV4cCI6MjA4NTQ0OTIxMX0.9hARr9YjKj1zvomR4i4pU69OVv9QY0V21PJBUFBcu8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});